modLoader="javafml"
loaderVersion="[36,)"
license="Apache-2.0"
issueTrackerURL="https://github.com/LXGaming/ProxyProtocol/issues"

[[mods]]
modId="proxyprotocol"
version="${version}"
displayName="ProxyProtocol"
displayURL="https://lxgaming.github.io/"
logoFile="lxgaming.png"
credits="LX_Gaming"
authors="LX_Gaming"
description="ProxyProtocol\nSource - https://github.com/LXGaming/ProxyProtocol"